# Generated by Django 3.2.8 on 2021-10-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrempresa', models.CharField(max_length=30)),
                ('propietario', models.CharField(max_length=30, unique=True)),
                ('cantorq', models.CharField(max_length=5)),
                ('contacto', models.CharField(max_length=9)),
                ('ubicacion', models.CharField(max_length=30)),
            ],
        ),
    ]
